### ISSUE TITLE
TypeError when starting project

### ISSUE THREAD

**Issue by nixolas1** [pinqy520/three-typescript-starter#3]
clone -> install -> start ->

TypeError: Cannot read property 'properties' of undefined
at module.exports node_modules\webpack-cli\bin\config-yargs.js:89:48

**Comment by ziuniecki** [comment]
I think 'latest' in package.json isn't good idea :) 
try to update package.json
`"webpack-cli": "^3.0.8",`

 and install dependencies again.

it works for me! :)
